# Project information
site_name: Yocto/GL
site_author: Fabio Pellacini

# Repository
repo_name: xelatihy/yocto-gl
repo_url: https://github.com/xelatihy/yocto-gl/
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2016 - 2020 Fabio Pellacini

# Theme
theme:
  name: material
  language: en
  extra_css:
    - css/extra.css

# Extensions
markdown_extensions:
  - codehilite
  - admonition

# Pages
nav:
  - About: index.md
  - Gallery: gallery.md
  - Math Types: yocto/yocto_math.md
  - Color Utilities: yocto/yocto_color.md
  - Geometry Utilities: yocto/yocto_geometry.md
  - Sampling Utilities: yocto/yocto_sampling.md
  - Noise Functions: yocto/yocto_noise.md
  - Shading Utilities: yocto/yocto_shading.md
  - Image Processing: yocto/yocto_image.md
  - Shape Processing: yocto/yocto_shape.md
  - Mesh Processing: yocto/yocto_mesh.md
  - Model IO: yocto/yocto_modelio.md
  - Scene Representation: yocto/yocto_scene.md
  - Scene IO: yocto/yocto_sceneio.md
  - Scene Rendering: yocto/yocto_trace.md
