name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: packages
      run: |
        sudo apt-get update --yes
        sudo apt-get install --yes cmake
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: |
        make -j8
